os: linux
sudo: true
language: python

services:
	- mysql

python:
  - "3.6"

before_install:
  - sudo mysql -e 'CREATE DATABASE AquaSaying;'

install:
  - pip install -r requirements.txt
script:
  - python3 ./server/app.py
cache:
  - pip
branches:
  only:
    - master

notifications:
  email: false